### ISSUE TITLE
mouseevents after ajax load?

### ISSUE THREAD

**Issue by metalmatze** [johan/gravatar-zoom#2]
Hey, after a ajax load the images aren't load.

Is this a known issue?
Is there a way you could fix this?

I've played around with something like this:

```
$i.live({mouseenter:function(){
        grow
    },mouseleave:function(){
        shrink
}});
```

But this doesn't work either...
This is the last feature of this really cool exentions, that I'd like to see! :)

**Comment by johan** [comment]
Amusingly, I was tinkering a little with this very thing yesternight, but haven't had the time to try it out yet – does the latest master (with https://github.com/johan/gravatar-zoom/commit/deb97749587f621939f7c0eb52cce9012f0a5c6f?w=1) seem to work better?

(In order to work well, it needs to have only one `mouseenter` or `mouseleave` handler active for any hovered image, which the quick'n'dirty initial implementation did by hooking up both events for all images that existed at load time.)

**Comment by metalmatze** [comment]
Alright. 
This is nice!
It work's fine after loading content via ajax.

But when you take a look at: http://metalmatze.de and hover the picture of me, the animation doesn't work quite as it should...
Instead of zooming from the center picture seems to zoom from the top left.

**Comment by johan** [comment]
If that's a different problem unrelated to this one (i e: it existed before this change), it should be in a separate issue.

(Seems like a timing issue or similar in the grow code, as it doesn't seem to zoom back down to the top left corner.)
